import React,{useState,useRef,useEffect} from 'react'
import { HiChatAlt2,HiX,HiPaperAirplane } from 'react-icons/hi'
const KB=[
{keys:['rag','retrieval','sec','financial document'],text:'At Morgan Stanley, Lakshmi architected a RAG financial document intelligence platform using LangChain, Pinecone and GPT-4, enabling 200+ equity research analysts to query SEC filings with sub-2s latency. Her resume project work also includes a multimodal RAG system over 1,200+ annual reports using hybrid Pinecone + BM25 retrieval and Cohere Rerank, improving retrieval accuracy by 28%.'},
{keys:['morgan','current','experience'],text:'Lakshmi is an AI/ML Engineer at Morgan Stanley (Aug 2025–Present). Her work includes production RAG, LLaMA-2-13B LoRA fine-tuning, Kubernetes/NVIDIA Triton inference, SageMaker-Airflow-MLflow pipelines, Evidently/Prometheus/Grafana observability, and SHAP-based model governance.'},
{keys:['dell','recommendation','support ticket'],text:'At Dell Technologies (Jun 2021–Jul 2023), Lakshmi built a PyTorch recommendation system processing 800K daily interactions, a BERT support-ticket classifier trained on 140K+ tickets, PySpark feature pipelines over 12 TB of telemetry, and XGBoost predictive-maintenance models on GCP.'},
{keys:['llama','lora','fine-tun'],text:'Lakshmi fine-tuned LLaMA-2-13B using LoRA/PEFT on 500K+ earnings-call tokens, improving financial sentiment classification F1 from 0.71 to 0.89.'},
{keys:['triton','latency','kubernetes','serving'],text:'She engineered Kubernetes-native model serving with NVIDIA Triton, reducing portfolio-risk inference latency from 340ms to 85ms for 12K daily production requests.'},
{keys:['mlops','airflow','mlflow','monitor'],text:'Her MLOps stack includes MLflow, Airflow, Kubeflow, Docker, Kubernetes, NVIDIA Triton, Evidently AI, Prometheus and Grafana. At Morgan Stanley, SageMaker + Airflow + MLflow reduced multi-week retraining cycles to 4 days across 6 risk models.'},
{keys:['fraud','anomaly','kafka'],text:'In her Real-Time Enterprise Anomaly & Fraud Detection project, Lakshmi built Kafka + Spark Streaming pipelines at 5,000 events/sec and a PyTorch autoencoder reaching 0.94 PR-AUC with under-15ms inference using Redis caching.'},
{keys:['stock','lstm'],text:'Her Stock Market Prediction project uses LSTM networks, 15 technical indicators and 60-day historical windows. Hyperparameter tuning achieved 0.042 RMSE and outperformed moving-average baselines.'},
{keys:['land','satellite','cnn','vision'],text:'Her Land Use Classification project trained a CNN on 25,000 satellite images across 3 land-use classes, with OpenCV preprocessing and augmentation across 8 geographic regions, achieving 0.92 overall F1.'},
{keys:['skill','technology','stack'],text:'Core skills include PyTorch, TensorFlow, scikit-learn, XGBoost, Hugging Face, BERT, LLaMA-2, RAG, LangChain, LlamaIndex, PEFT/LoRA, GPT-4, Pinecone, MLflow, Airflow, Kubeflow, NVIDIA Triton, Docker, Kubernetes, Spark, PySpark, Kafka, AWS, GCP, Azure, OCI, Python, SQL, Scala and Bash.'},
{keys:['education','master','university'],text:'Lakshmi earned an M.S. in Artificial Intelligence from the University of North Texas (Aug 2023–May 2025) and a B.E. in Computer Science from Stanley College of Engineering & Technology for Women (Jul 2019–Jun 2023).'},
{keys:['cert','oracle','google data'],text:'Her listed certifications are OCI 2025 Certified Generative AI Professional, OCI 2025 Certified AI Foundations Associate, AI For Everyone (DeepLearning.AI), Python for Data Science, AI & Development (IBM), and Google Data Analytics Professional Certificate.'},
{keys:['contact','email','linkedin','github','hire'],text:'Contact Lakshmi at lakshmiprasannav8124@gmail.com. LinkedIn: linkedin.com/in/prasanna-v08. GitHub: github.com/lakshmi-prasanna-8.'},
{keys:['year','background','summary'],text:'Lakshmi is an AI/ML Engineer with 3+ years of experience architecting and deploying production-scale machine learning systems, specializing in LLMs, RAG, MLOps, PyTorch and Kubernetes-native model serving.'},]
const suggestions=['Tell me about your RAG experience','What did you build at Morgan Stanley?','Tell me about the fraud detection project','What are your core AI/ML skills?']
function answer(q){const s=q.toLowerCase();let best=null,score=0;for(const x of KB){const n=x.keys.filter(k=>s.includes(k)).length;if(n>score){best=x;score=n}}return best?.text||"I don't have that detail in Lakshmi's current portfolio knowledge base. You can contact her at lakshmiprasannav8124@gmail.com."}
export default function ChatWidget(){const[o,setO]=useState(false),[msgs,setMsgs]=useState([{role:'a',text:"Hi! I'm Lakshmi's portfolio assistant. Ask me about her resume, experience, projects, skills, education, or certifications."}]),[input,setInput]=useState('');const ref=useRef();useEffect(()=>{if(ref.current)ref.current.scrollTop=ref.current.scrollHeight},[msgs]);const send=(t)=>{const q=(t||input).trim();if(!q)return;setMsgs(m=>[...m,{role:'u',text:q},{role:'a',text:answer(q)}]);setInput('')};return <><button onClick={()=>setO(!o)} className="fixed bottom-6 right-6 z-50 w-14 h-14 rounded-full bg-brandRed text-white flex items-center justify-center shadow-xl">{o?<HiX/>:<HiChatAlt2/>}</button>{o&&<div className="fixed bottom-24 right-6 z-50 w-[90vw] max-w-sm h-[30rem] bg-[#111] border border-white/10 rounded-2xl shadow-2xl flex flex-col overflow-hidden"><div className="px-4 py-3 bg-brandRed"><p className="font-display font-bold">Ask about Lakshmi</p><p className="text-white/75 text-[10px] uppercase tracking-widest">Resume-aware portfolio assistant</p></div><div ref={ref} className="flex-1 overflow-y-auto p-4 flex flex-col gap-3">{msgs.map((m,i)=><div key={i} className={`max-w-[88%] px-3 py-2 rounded-xl text-sm ${m.role==='u'?'self-end bg-brandRed':'self-start bg-white/10 text-white/90'}`}>{m.text}</div>)}{msgs.length===1&&<div className="flex flex-col gap-2">{suggestions.map(q=><button key={q} onClick={()=>send(q)} className="text-left text-xs text-white/70 border border-white/15 rounded-lg px-3 py-2">{q}</button>)}</div>}</div><form onSubmit={e=>{e.preventDefault();send()}} className="border-t border-white/10 p-3 flex gap-2"><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask about the resume..." className="flex-1 bg-white/5 border border-white/10 rounded-full px-4 py-2 text-sm text-white outline-none"/><button className="w-10 h-10 rounded-full bg-brandRed flex items-center justify-center"><HiPaperAirplane className="rotate-90"/></button></form></div>}</>}
