import React from 'react'
import { motion } from 'framer-motion'
const PROJECTS=[
{title:'Multimodal Financial Document Intelligence & QA',tag:'GenAI · RAG · Financial AI',points:['End-to-end RAG pipeline for 1,200+ annual reports with cross-modal table and chart parsing.','Hybrid Pinecone dense retrieval + BM25 sparse search with Cohere Rerank, boosting retrieval accuracy by 28%.','Docker + FastAPI deployment achieving sub-1.5s query-to-response latency.']},
{title:'Real-Time Enterprise Anomaly & Fraud Detection Engine',tag:'Streaming ML · PyTorch · MLOps',points:['Kafka + Spark Streaming architecture evaluating transaction streams at 5,000 events/sec.','PyTorch autoencoder achieved 0.94 Precision-Recall AUC with <15ms inference using Redis feature caching.','MLflow lifecycle/versioning enabled zero-downtime hot swapping across 4 model iterations during feature drift.']},
{title:'Stock Market Prediction using LSTM',tag:'Deep Learning · Time Series',points:['LSTM forecasting from historical market data and 15 technical indicators across multi-day horizons.','60-day historical sequence generation with preprocessing and feature engineering for non-stationary data.','Tuned using RMSE and MAE, achieving 0.042 RMSE and outperforming moving-average baselines.']},
{title:'Land Use Classification using CNN',tag:'Computer Vision · CNN',points:['CNN trained on 25,000 high-resolution satellite images across 3 land-use categories.','OpenCV preprocessing and augmentation supported generalization across 8 geographic regions and lighting conditions.','Achieved 0.92 overall F1-score while monitoring class imbalance and bias.']},]
const GH=[['Enterprise RAG Pipeline','https://github.com/lakshmi-prasanna-8/enterprise-rag-pipeline'],['Fraud Detection MLOps','https://github.com/lakshmi-prasanna-8/fraud-detection-mlops'],['Agentic Support Triage','https://github.com/lakshmi-prasanna-8/agentic-support-triage'],['Clinical NLP Pipeline','https://github.com/lakshmi-prasanna-8/clinical-nlp-pipeline']]
export default function Projects(){return <section id="projects" className="bg-[#0a0a0a] py-24 md:py-32"><div className="max-w-7xl mx-auto px-6 md:px-10"><span className="inline-block rounded-full border border-white/15 px-4 py-1.5 text-xs font-mono-wide uppercase text-white/60">Selected Projects</span><h2 className="font-display font-extrabold text-white text-4xl sm:text-6xl mt-6">Projects from my resume.</h2><p className="mt-5 max-w-2xl text-white/55">The projects below preserve the technical scope and measurable results highlighted on my current resume.</p><div className="mt-14 grid md:grid-cols-2 gap-6">{PROJECTS.map((p,i)=><motion.article key={p.title} initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true}} className="rounded-[2rem] border border-white/10 bg-white/[.03] p-7 hover:border-brandRed/60 transition-colors"><p className="font-mono-wide uppercase text-[10px] text-brandRed">{p.tag}</p><h3 className="font-display font-bold text-white text-2xl mt-3">{p.title}</h3><ul className="mt-5 space-y-3 text-sm text-white/65">{p.points.map(x=><li key={x} className="flex gap-3"><span className="text-brandRed">●</span><span>{x}</span></li>)}</ul></motion.article>)}</div><div className="mt-16"><h3 className="font-display font-bold text-white text-2xl">Public GitHub projects</h3><div className="mt-5 flex flex-wrap gap-3">{GH.map(([n,u])=><a key={u} href={u} target="_blank" rel="noreferrer" className="rounded-full border border-white/15 px-4 py-2 text-sm text-white/70 hover:border-brandRed hover:text-white">{n} ↗</a>)}</div></div></div></section>}
