import React from 'react'
import { motion } from 'framer-motion'
const CATEGORIES=[
{title:'AI/ML & Deep Learning',items:['PyTorch','TensorFlow','scikit-learn','XGBoost','LightGBM','Hugging Face Transformers','BERT','LLaMA-2','NLP','Computer Vision','CNN']},
{title:'Generative AI & LLMs',items:['LLMs','RAG','LangChain','LlamaIndex','Prompt Engineering','PEFT / LoRA','GPT-4','Mistral','Pinecone','ChromaDB','Weaviate']},
{title:'MLOps & Infrastructure',items:['MLflow','Apache Airflow','Kubeflow','NVIDIA Triton','Docker','Kubernetes','CI/CD','Evidently AI','Model Monitoring','Feast','BentoML']},
{title:'Cloud & Data Engineering',items:['AWS','SageMaker','GCP','Azure','OCI','Apache Spark','PySpark','Kafka','Snowflake','Databricks']},
{title:'Programming & Databases',items:['Python','SQL','Scala','Bash','PostgreSQL','MongoDB','Redis','Elasticsearch','REST APIs','GraphQL']},
{title:'Tools & Methodologies',items:['Git','GitHub','Terraform','Prometheus','Grafana','SHAP','Agile / Scrum','Responsible AI','Model Risk Management','Jupyter']},]
const CERTS=['OCI 2025 Certified Generative AI Professional','OCI 2025 Certified AI Foundations Associate','AI For Everyone — DeepLearning.AI','Python for Data Science, AI & Development — IBM','Google Data Analytics Professional Certificate']
export default function Skills(){return <section id="skills" className="bg-[#0a0a0a] py-24 md:py-32"><div className="max-w-7xl mx-auto px-6 md:px-10"><span className="inline-block rounded-full border border-white/15 px-4 py-1.5 text-xs font-mono-wide uppercase text-white/60">Technical Toolkit</span><h2 className="font-display font-extrabold text-white text-4xl sm:text-6xl mt-6">Built for production AI.</h2><div className="mt-14 grid md:grid-cols-2 lg:grid-cols-3 gap-px bg-white/10 rounded-2xl overflow-hidden">{CATEGORIES.map((c,i)=><motion.div key={c.title} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} className="bg-[#0a0a0a] p-7"><h3 className="font-display font-bold text-white text-lg mb-5">{c.title}</h3><div className="flex flex-wrap gap-2">{c.items.map(x=><span key={x} className="rounded-full border border-white/10 px-3 py-1.5 text-xs text-white/65">{x}</span>)}</div></motion.div>)}</div><div className="mt-16"><h3 className="font-mono-wide uppercase text-xs text-white/40 mb-5">Certifications</h3><div className="flex flex-wrap gap-3">{CERTS.map(c=><span key={c} className="rounded-full border border-white/15 px-4 py-2 text-xs text-white/70">{c}</span>)}</div></div></div></section>}
