import React from 'react'
import Preloader from './components/Preloader'
import Navbar from './components/Navbar'
import Hero from './components/Hero'
import About from './components/About'
import Skills from './components/Skills'
import Experience from './components/Experience'
import Projects from './components/Projects'
import Education from './components/Education'
import Footer from './components/Footer'
import ChatWidget from './components/ChatWidget'
export default function App(){return <><Preloader/><Navbar/><main><Hero/><About/><Skills/><Experience/><Projects/><Education/></main><Footer/><ChatWidget/></>}
